name: Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: build image 
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/lavanya:v1
    - name: docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lavanya:v1
  
